name: Release
on:
  push:
    tags: [v**]
jobs:
  release:
    runs-on: ubuntu-latest
    name: Build and Publish Python distributions to PyPI
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11
        architecture: x64
    - name: Install requirements
      run: pip install build
    - name: Build distributions
      run: python -m build
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
        print_hash: true
        packages_dir: dist
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
